### ISSUE TITLE
LoadArff() in AnnotateData.m not defined

### ISSUE THREAD

**Issue by ghost** [MikhailStartsev/deep_em_classifier#1]
Hello, 

thanks a lot for publishing this great tool. I wanted to try it using my own data, following the instructions provided in your readme file. However, when I'm running AnnotateData.m Matlab raises an Error: Undefined function or variable 'LoadArff'.

I have tried several matlab add-ons, but none of them includes a function exactly matching LoadArff() and neither of them really works. Is this a function you have written yourself or which matlab add-on did you use?

**Comment by MikhailStartsev** [comment]
Please check the latest version now. Added the missing files, updated the README for the feature_extraction part.

**Comment by ghost** [comment]
Great, it works now, thank you.
