### ISSUE TITLE
about train_X and train_Y

### ISSUE THREAD

**Issue by mmppllhaha** [MikhailStartsev/deep_em_classifier#2]
Thank you very much. Your work is truly groundbreaking. But I don't know why train_X[1].shape is 71, and train_Y[1].shape is 65, what does it mean?

**Comment by MikhailStartsev** [comment]
Dear @mmppllhaha ,

Thank you for the interest in our work! As you can see on the plot of the network data pipeline (first picture on the [project page](https://github.com/MikhailStartsev/deep_em_classifier#description)), each Conv1D operation is of size 3, and uses "valid" padding, so it "cuts off" 1 sample from each side of the window. Depending on the number of such Conv1D layers in the network, the length of windows in X changes, if a constant window size in Y is maintained. E.g. for a Y-window of 65 samples and an X-window of 71 samples, the architecture has (71-65)/2=3 convolutional layers with valid padding.

If you want to train this network for your own experiments, you can simplify the pipeline by using "same" padding, in which case the input and output windows will have the same size. This should not affect the performance too much, but we wanted to avoid dealing with potential artefacts.

Also, just in case, for better performance, especially for smooth pursuit detection, we recommend larger window sizes.

Best regards,
Mikhail
